# my python note#
this is my python exercises.

In [1]:

a = range(1,10,1)
for aa in a:
    print(aa)
print(a,len(a))

1
2
3
4
5
6
7
8
9
range(1, 10) 9


In [2]:
a = range(1,10,1)
b = range(31,40)
type(a)
c = a 
#d = a * b
print (c)
#print(d)

range(1, 10)


In [7]:
#list operation
a = [1,2,3,4]
b = [4,5,6,7]
try:
    #c= a - b # unsupported operand type for -: "list"
    d = b * 2
except Exception as e:
    print(e)
print(d)

SyntaxError: invalid syntax (<ipython-input-7-e2337609d3de>, line 7)

In [4]:
#tuple operation
a = (1,2,3,4)
try:
    #b = a/2
    c = a * 2
except Exception as e:
    print (e)
print(c)

(1, 2, 3, 4, 1, 2, 3, 4)


# array operating

In [23]:
#array
from numpy import *
a=array([1,2,3,4])
b=arange(4)
print(a,b)
c=a+b
print(c)
d= a * b
print(d)
e=array([[1,2],[3,4]])
f=array([[1,1],[0,2]])
h=e*f
array_dot = dot(e,f)
print("e*f={}".format(h))
print ("===array_dot==")
print(array_dot)

[1 2 3 4] [0 1 2 3]
[1 3 5 7]
[ 0  2  6 12]
e*f=[[1 2]
 [0 8]]
===array_dot==
[[ 1  5]
 [ 3 11]]
